### ISSUE TITLE
2015-01-11

### ISSUE THREAD

**Issue by waynezhang87** [liaohuqiu/qq-tribe-rule#3]
Kiss dream  10:58:45
gson 怎么转  求指点
神的孩子  10:59:08
google一下
廖祜秋  10:59:13
大哥，这个问题不是你应该问出来的。

Kiss dream  11:09:12
廖祜秋  10:59:13  问题该怎么问那是我自己的事情

**Comment by liaohuqiu** [comment]
合并到 #1
